### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by JackieZHU316** [JackieZHU316/furima-37930#20]
●自身のフリマアプリのURL
https://furima-37930.herokuapp.com/

●Basic認証のIDとパスワード
ID：admin
パスワード：2222

●出品者用のメールアドレスとパスワード
メールアドレス：test@test.jp
パスワード：aaa111

●購入者用のメールアドレスとパスワード
メールアドレス：test@test.com
パスワード：aaa111

**Comment by motomuun** [comment]
@JackieZHU316 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品出品機能の確認**

- [x] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されること（--- は初期値として設定すること）**
項目名が微妙に異なります。正しい名称に修正をお願いします。
<img width="1440" alt="スクリーンショット 2022-09-26 9 37 25" src="https://user-images.githubusercontent.com/65059944/192173439-67a08ab4-19a8-42d9-8d75-9c558fcdee41.png">

**商品購入機能の確認**

- [x] **クレジットカード情報は必須であり、下記のPAY.JPテストカードの情報で決済ができること**

```
カード情報
・カード番号：4242424242424242
・有効期限：今日より未来の日付
・セキュリティコード：123
```
「Token can't be blank」と表示され決済することが出来ませんので、決済が出来るように修正をお願いします。

※売却済みの商品に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by JackieZHU316** [comment]
ご連絡ありがとうございました！

カテゴリーの項目に関しては、誤記で確認不足でした。
見つけて頂きましてありがとうございました！
不具合部分を修正しましたので、再度にご確認をお願いいたします。

クレジットカード決済の件については、テスト環境でしか確認しませんでしたが、
herokuへの本番環境の設定は行いませんでした。失礼しました。
現在設定などを行い、自らで本番環境の動作確認を実施しました。
お手数ですが、再度のご確認をお願いいたします。

以上です。よろしくお願いいたします。

**Comment by snkw-works** [comment]
@JackieZHU316 さん、修正とご提出ありがとうございます‼︎
動作の確認をしたところ、前回お伝えした点については修正が確認できました。ありがとうございます。
引き続き、修正していただきたい箇所がございましたので、以下のご確認をお願いします！

[修正依頼箇所]
- [x] **ログイン状態の場合でも、自身が出品していない商品の商品情報編集ページへ遷移しようとすると、商品の販売状況に関わらずトップページに遷移するよう修正しましょう**
自身が出品していない"売却済"商品の商品情報編集ページへ遷移しようとすると、エラー画面に遷移してしまいます。
<img width="742" alt="スクリーンショット 2022-09-27 9 42 28" src="https://user-images.githubusercontent.com/54050089/192405523-7c8fead8-dce7-4b71-b9e3-4ae2619bed8a.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by JackieZHU316** [comment]
ご連絡ありがとうございました。
要求仕様理解不十分でしたので失礼しました。
プログラムを修正し、自分自身で本番環境で動作チェックを行いました。
大変恐れ入りますが、再度の承認をよろしくお願いいたします。

**Comment by motomuun** [comment]
@JackieZHU316 さん、フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した最終課題ガイダンス資料にてご確認いただきますようお願いいたします。

＜最終課題ガイダンス資料の再確認＞
最終課題フェーズに入る直前に確認いただいた資料と同じものですが、必ず確認の上、次の学習に取り組みましょう。
とりわけ、資料の「3. 悩んだ際のアクション」については、改めてよく確認するようにしてください。
https://master.tech-camp.in/v2/curriculums/7681

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。

![lgtm_01](https://user-images.githubusercontent.com/65059944/192663208-7252ce09-f692-49bb-bf3a-cbf87309de40.png)
